# dev
version: '3.7'

services:
  webapp:
    container_name: webapp
    build:
      context: ./webapp
    volumes:
      - ./webapp:/app
    ports:
      - "3999:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  servicenode:
    container_name: servicenode
    build:
      context: ./service-templating-downloading
      dockerfile: Dockerfile
    volumes:
      - ./service-templating-downloading:/app
    ports:
      - "4000:4000"
  api:
    container_name: api
    build:
      context: ./api
    volumes:
      - ./api/cmd:/go/src/api/cmd
    ports:
      - "8080:8080"
